### ISSUE TITLE
升级guacd后，所有windows不能再连接。换回之前版本正常

### ISSUE THREAD

**Issue by xiefei0826** [jumpserver/Dockerfile#110]
v2.17.3 后修改了guacd 版本，导致后续版本不能连接。一直报 “无法连接 Guacamole 服务器”  完全重新安装的是正常的。这个是不是数据库那里有配置？找了所有字段没有那个像是调整这个了

**Comment by xiefei0826** [comment]
还原到老版本正常

**Comment by wojiushixiaobai** [comment]
无法复现，需要看看具体的报错
