### ISSUE TITLE
ERROR: Service "core" uses an undefined network "net"

### ISSUE THREAD

**Issue by jesse-zhangh** [jumpserver/Dockerfile#128]
标准部署v2.21.4，
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
docker-compose version 1.25.0, build unknown
Ubuntu20.04

已配置完成mysql和redis
执行
docker-compose -f docker-compose-init-db.yml up -d
报错：
ERROR: Service "core" uses an undefined network "net"

sudo docker network ls
6dc01d857dd1   jms_default   bridge    local
12e3aaede4f6   jms_net       bridge    local

请问一下怎么处理呢?
感谢了

**Comment by wojiushixiaobai** [comment]
更新下代码，重新按照说明部署即可，缺少网络配置导致。

**Comment by jesse-zhangh** [comment]
谢谢，没问题了。
