### ISSUE TITLE
[Question] 部署后web cli无法连接资源

### ISSUE THREAD

**Issue by jesse-zhangh** [jumpserver/Dockerfile#131]
**请描述您的问题.**
打开web终端，访问服务部署的本机，无法连接，错误：
资源ip  says
打开地址失败：
http://资源ip/koko/terminal/target_id=xxx&type=ssh&system_user_id=xxxx&disableauthhash=&_xxxx

ssh client, 已安装客户端，提示连接超时，网络错误

已检查：
1 6个容器正常，healthy
2 管理资源为jms部署服务器，网络正常，本机已测试认证凭证均正常
3 测试jms部署服务器访问同网段其他服务器，部署服务器测试正常，但jms访问报错同上描述
4 数据库访问jms数据库，报错同上，client提示的命令行，复制可正常访问数据库

请问该怎么排查呢? 怀疑是部署的问题？

**Comment by jesse-zhangh** [comment]
补充信息：jumpserver部署在aws上，管理aws的ec2和部署在ec2上的mysql

**Comment by wojiushixiaobai** [comment]
从容器里面访问你要访问的资产看看结果

**Comment by jesse-zhangh** [comment]
重新部署了一遍，可以了，应该是部署问题。
另，请教一下，管理aws的eks，token是serviceaccount的，还是user的呢?
本地测试自行部署的k8s，sa的token是可以访问的，但eks目前测试没成功
谢谢。

**Comment by wojiushixiaobai** [comment]
暂时无 aws 环境测试，没法提供更多建议

**Comment by jesse-zhangh** [comment]
部署问题，重新部署后解决此问题。
