### ISSUE TITLE
[Bug] 多个bug

### ISSUE THREAD

**Issue by w1th1c3** [jumpserver/Dockerfile#141]
**JumpServer 版本(v1.5.9以下不再支持)**
Version v2.23.2 GPLv2.

**浏览器版本**
Chrome
版本 102.0.5005.115

**Bug 描述**
1. 登录界面的html资源错误，输入密码的 input标签被设置成display:none ，导致怎么输入密码都会报错提示该字段为空
![图片](https://user-images.githubusercontent.com/81949263/176155028-a887f2ac-6b46-4bc6-851d-0e5899a6afc9.png)
需要手动把display:none去掉后再输入密码，才能登陆
![图片](https://user-images.githubusercontent.com/81949263/176155295-a6c3e4ba-d3ba-44cc-aaf5-059567985b5e.png)

2. 当使用allinone中的方法快速搭建时，如果在通过docker -e指定外部redis的ip端口密码，则无法成功运行jumpserver，尝试登录web页面时会不断报 502的错误，从而一直卡在空白的首页中
只能使用jms_all中的内置redis才能成功运行
https://github.com/jumpserver/Dockerfile/tree/master/allinone

**Comment by wojiushixiaobai** [comment]
问题1，清理浏览器缓存
问题2，自行解决网络问题
