### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by andyoulovexy** [jumpserver/Dockerfile#148]
**请描述您的问题.**v2.5.3升级到v2.24.0 正常，登陆之后报错
![image](https://user-images.githubusercontent.com/38940994/180735139-d03f316a-e679-4242-a192-9dfddeeb091b.png)

**Comment by wojiushixiaobai** [comment]
看看 core 日志

**Comment by andyoulovexy** [comment]
> 看看 core 日志
日志只有这些
![image](https://user-images.githubusercontent.com/38940994/180908382-7c563456-9ae1-441c-a1cf-703af84c0bb9.png)
![image](https://user-images.githubusercontent.com/38940994/180908555-56c69764-b0d2-4e53-9e2b-eec4da482a5f.png)

**Comment by wojiushixiaobai** [comment]
在容器的 /opt/jumpserver/logs/jumpserver.log

**Comment by andyoulovexy** [comment]
> 在容器的 /opt/jumpserver/logs/jumpserver.log
是redis版本太低吗？我原来的redis是3.2.12，对应的redis是否需要迁移？
![image](https://user-images.githubusercontent.com/38940994/180969126-c1a0ca22-6d8c-4aee-9fcc-48e833c3f479.png)

**Comment by wojiushixiaobai** [comment]
参考官方文档的组件要求，
redis 需要 >= 5.0
