### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ku666** [jumpserver/Dockerfile#158]
**JumpServer 版本(v1.5.9以下不再支持)**
jumpserver/jms_all:v2.25.4、jumpserver/jms_all:v2.25.3

**浏览器版本**
版本 104.0.5112.101（正式版本） (x86_64)

**Bug 描述**
在测试资产连接性时 告知ssh不存在 其他的都可以正常连接
FAILED! => {"msg": "Unable to execute ssh command line on a controller due to: [Errno 2] No such file or directory: b'ssh'"}

**Bug 重现步骤(有截图更好)**
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/30383748/189870360-83624ca0-ac01-4f36-b501-ef4845ec275a.png">

**Comment by wojiushixiaobai** [comment]
- #157 
v2.25.5 已经修复，感谢。
