### ISSUE TITLE
[Bug] jms_web一直在重启

### ISSUE THREAD

**Issue by zealinux** [jumpserver/Dockerfile#165]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.28.1

**浏览器版本**
无

**Bug 描述**
jms_web一直在重启

**Bug 重现步骤(有截图更好)**
1.  nginx: [emerg] invalid number of arguments in "listen" directive in /etc/nginx/conf.d/default.conf:2

**Comment by wojiushixiaobai** [comment]
参考 #166 此 pr 修正下，或者更新下 Dockerfile 代码即可。

由于 https://github.com/jumpserver/docker-web/blob/master/init.sh#L7 启动脚本缺少判断变量 HTTP_PORT 是否存在导致
