### ISSUE TITLE
[Question] docker-compose ps

### ISSUE THREAD

**Issue by zealinux** [jumpserver/Dockerfile#167]
**请描述您的问题.**
在执行 `docker-compose -f docker-compose-network.yml     -f docker-compose.yml ps` 时发现**jms_magnus**的端口显示太多

![CleanShot 2022-11-25 at 16 16 24@2x](https://user-images.githubusercontent.com/167025/203934007-ce980df6-5688-4dc4-9175-46e134099c45.jpg)

**Comment by wojiushixiaobai** [comment]
升级 docker-compose 到 v2 版本，这个是由于我们制作镜像时配置不当在申明端口范围的时候写成了
```dockerfile
EXPOSE 0-65535 
```
导致，我们会在下个版本修复，这些端口只是标识，没有实际使用。
