### ISSUE TITLE
[Question] docker-compose 部署时，magnus_ports 在哪边配置

### ISSUE THREAD

**Issue by hanbinpro** [jumpserver/Dockerfile#173]
请问 docker-compose 部署时，magnus_ports 在哪边配置，我在 .env 配置后，重新构建后没有生效。

**Comment by wojiushixiaobai** [comment]
[docker-compose.yml](https://github.com/jumpserver/Dockerfile/blob/master/docker-compose.yml)

**Comment by hanbinpro** [comment]
> 

这个只增加了端口映射，但是没有改到 magnus 和 core 的配置。
最终在技术支持的协助下修改了 core 的 envirnment 配置才生效。
如果可以的话建议这里要优化一下。

<img width="372" alt="image" src="https://user-images.githubusercontent.com/13300451/215255161-698d99b0-e976-4e33-94ed-f01bd34cc3c1.png">
