### ISSUE TITLE
3.x 什么时候安排一下

### ISSUE THREAD

**Issue by Rehtt** [jumpserver/Dockerfile#178]

**Comment by clangcn** [comment]
同样等3.x的allinone

**Comment by wojiushixiaobai** [comment]
@Rehtt @clangcn 我们已经收到了类似的请求，如果有更多的用户期望 v3 版本继续迭代的话我们将会重新更新此项目。感谢关注

**Comment by ibuler** [comment]
我把 issue 挪到 jumpserver 项目中，去 https://github.com/jumpserver/jumpserver/issues/10073 查看
