### ISSUE TITLE
IPv6问题

### ISSUE THREAD

**Issue by litongjava** [jumpserver/Dockerfile#26]
我的运行命令如下
docker run --name jms_all -d -p 81:80 -p 2222:2222 -e SECRET_KEY=$SECRET_KEY -e BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN jumpserver/jms_all:latest
启动后发现日志如下
guacd[251]: INFO:	Guacamole proxy daemon (guacd) version 0.9.14 started
Starting guacd: SUCCESS
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
容器内的nginx启动失败,原因是我的服务器不支持IPV6,能不能重新生成一个镜像,去除IPV6,使用IPv5

**Comment by wojiushixiaobai** [comment]
@litongjava 进入容器手动处理下，或者修改docker的相关配置文件
