### ISSUE TITLE
无法配置Mailgun邮件发送服务

### ISSUE THREAD

**Issue by jaggerwang** [jumpserver/Dockerfile#3]
![image](https://user-images.githubusercontent.com/1255011/37822164-ab285008-2ec0-11e8-986e-131cfe5f976e.png)
点击“测试连接”，提示邮件已发送，但始终收不到。另外添加新用户时，新用户也无法收到邮件（阿里云企业邮箱）。

**Comment by liuzheng** [comment]
去掉ssl这个勾

**Comment by jaggerwang** [comment]
去掉SSL勾选就报错阿，“{"error":"Connection unexpectedly closed: timed out"}”。有效的Issue不应该是提交者来关闭吗？

**Comment by liuzheng** [comment]
@ibuler

**Comment by liuzheng** [comment]
功能issue请提到jumpserver里，然后我们并不打算完全维护这个docker image，原因我在readme里已经说明了，这个docker image存在docker自身的问题，无法解决，请自行尝试手工部署

**Comment by jaggerwang** [comment]
至少保证基本功能可用吧...。如果基本流程都不通，也不打算提供技术支持，那就最好不好放在文档里，否则会误导大家，浪费大家的时间。

**Comment by liuzheng** [comment]
额。。。我们初衷是让大家能方便部署，怎么就遭罪了呢，这个是docker的问题啊，你这边只测到了邮件问题，我们测了其他问题，这点已经再首页readme里说明了。我们的技术精力有限，这个是docker的问题，我再强调一遍，这个是docker社区普遍认同的多进程在docker内运行会产生孤儿进程已经各种系统底层的问题，我们不提供docker的技术支持。

**Comment by ibuler** [comment]
你好，发送邮件需要重启jumpserver ，但是数据库在容器中重启就丢失了，你可以使用外置数据库，稍后设置好重启容器，谢谢

**Comment by ibuler** [comment]
在群里加我qq注明id，我帮你解决  446465001

**Comment by jaggerwang** [comment]
Docker里面并没有限制使用多线程，只是这不是最佳做法，一个容器只做一件事。我们现在部署的GitLab就是一个容器里运行所有的服务，包括应用服务器、数据库、缓存等，照样跑了一年多了。提点意见就觉得遭罪了，那也太玻璃心了。我理解很多做开源项目的人都是利用业务时间在做，精力有限，感谢大家的付出。我并没有要求你们非得提供docker技术支持，只是说如果没有精力支持，那最好不要把docker这种部署方式放在正式文档里，否则使用的人照着去做又走不通，岂不是浪费时间。

@ibuler 这个知道的，我们公司已经使用docker来做自动化部署一年多了。暂时不用了，我也只是想体验一下，现在手头事情比较多，有空再联系你。

**Comment by ibuler** [comment]
好的
