### ISSUE TITLE
web 终端打开输入命令时，经常会卡住几秒

### ISSUE THREAD

**Issue by HuangJT** [jumpserver/Dockerfile#33]
使用这个镜像：Jumpserver ALL 1.4.6
部署在K8S上， 可以正常使用，但就是web 终端打开输入命令时，经常会卡住几秒，基本上几分钟就会有一次，请问这个可能是什么原因呢？

**Comment by wojiushixiaobai** [comment]
@HuangJT 换个版本试试看，比如1.4.8
