### ISSUE TITLE
密钥我进docker里打通了，为啥添加主机后还是无法连上?

### ISSUE THREAD

**Issue by zhongerbingde** [jumpserver/Dockerfile#52]
密钥我进docker里打通了，为啥添加主机后还是无法连上?
在docker直接ssh连其他机器已经免密了。
宿主机也是免密的
难道跟账号有关系吗?免密不是在root账号下？

**Comment by wojiushixiaobai** [comment]
@zhongerbingde jumpserver不使用本地认证
