### ISSUE TITLE
ldap认证用户登录web显示：Server error occur, contact administrator

### ISSUE THREAD

**Issue by tuduni** [jumpserver/Dockerfile#58]
我使用docker jumpserver。数据库用户能正常登录使用，但是ldap用户能登录，但是提示“Server error occur, contact administrator”，不能使用。

**Comment by zhengwh2010** [comment]
看下你的用户过滤器怎么写的？我是用(sAMAccountName=%(user)s) 这种方式，那么LADP属性映射就必须写成{"username": "sAMAccountName", "name": "cn", "email": "mail"}
