### ISSUE TITLE
https://github.com/jumpserver/docker-guacamole/archive/v2.1.0.tar.gz  Not Found

### ISSUE THREAD

**Issue by dmanbu** [jumpserver/Dockerfile#63]
构建镜像的时候，拉取以下文件的时候提示找不到文件
wget https://github.com/jumpserver/docker-guacamole/archive/v2.1.0.tar.gz

看了下docker-guacamole项目，感谢被清空了似的

**Comment by wojiushixiaobai** [comment]
@dmanbu 构建方式已经变更，代码已经更新，请重试下
