### ISSUE TITLE
环境变量不支持DEBUG参数了吗

### ISSUE THREAD

**Issue by zjcnew** [jumpserver/Dockerfile#64]
环境变量不支持DEBUG: false了吗，这对k8s平台的部署实为不便。主要是想看api文档

**Comment by wojiushixiaobai** [comment]
@zjcnew 支持
建议生产环境单独起一个容器查看 api docs

**Comment by zjcnew** [comment]
> @zjcnew 支持
> 建议生产环境单独起一个容器查看 api docs

怎么操作

**Comment by wojiushixiaobai** [comment]
添加到环境变量就行，jumpserver 会读取系统变量
