### ISSUE TITLE
docker-compose 运行的mysql密码配置有误

### ISSUE THREAD

**Issue by taowujie** [jumpserver/Dockerfile#65]
在mysql的entrypoint.sh脚本中,通过```[ ! -d "/var/lib/mysql/$DB_NAME" ]; ``` 来设置jumpserver的密码.
但这个语句好像没有执行,/var/lib/mysql/jumpserver 目录一直存在,docker中mysql的密码一直是"weakPassword"

**Comment by wojiushixiaobai** [comment]
@taowujie 因为有持久化，所以需要判断数据库是否存在，如果存在则不会进行账户密码校验，你应该自己输入数据库的账户密码信息
