### ISSUE TITLE
[Bug] ./entrypoint.sh: line 33: /config/guacamole/data/log/info.log: No such file or directory

### ISSUE THREAD

**Issue by OPSTime** [jumpserver/Dockerfile#69]
**JumpServer 版本(v1.5.9以下不再支持)**
2.5.1
2.4.4

**Bug 描述**
jms_guacamole | ./entrypoint.sh: line 33: /config/guacamole/data/log/info.log: No such file or directory
jms_guacamole | tail: cannot open ‘/config/guacamole/data/log/info.log’ for reading: No such file or directory

**Comment by wojiushixiaobai** [comment]
@OPSTime 
https://github.com/jumpserver/Dockerfile/blob/master/guacamole/entrypoint.sh#L33
```
if [ ! -f "/config/guacamole/data/log/info.log" ]; then
    echo "" > /config/guacamole/data/log/info.log
fi
```

**Comment by OPSTime** [comment]
# 进入发现config/guacamole/data/log/目录不存在，和docker-compose配置中挂载目录有关！
# 加下判断，目录不存在就创建目录

$ cat guacamole/entrypoint.sh 

`uacamole]# cat entrypoint.sh 
#!/bin/bash
#

if [ ! $JUMPSERVER_KEY_DIR ]; then
    export JUMPSERVER_KEY_DIR=/config/guacamole/data/keys
fi
if [ ! $GUACAMOLE_HOME ]; then
    export GUACAMOLE_HOME=/config/guacamole
fi
if [ ! $GUACAMOLE_LOG_LEVEL ]; then
    export GUACAMOLE_LOG_LEVEL=ERROR
fi
if [ ! $JUMPSERVER_ENABLE_DRIVE ]; then
    export JUMPSERVER_ENABLE_DRIVE=true
fi

rm -rf /config/tomcat9/logs/*

sleep 5s
while [ "$(curl -I -m 10 -L -k -o /dev/null -s -w %{http_code} ${JUMPSERVER_SERVER}/api/health/)" != "200" ]
do
    echo "wait for jms_core ready"
    sleep 2
done

/etc/init.d/guacd start
cd /config/tomcat9/bin && ./startup.sh

echo "Guacamole version $Version, more see https://www.jumpserver.org"
echo "Quit the server with CONTROL-C."

**if [ ! -d "/config/guacamole/data/log/" ]; then 
    mkdir -p /config/guacamole/data/log/
fi**

if [ ! -f "/config/guacamole/data/log/info.log" ]; then
    echo "" > /config/guacamole/data/log/info.log
fi

tail -f /config/guacamole/data/log/info.log`

**Comment by wojiushixiaobai** [comment]
@OPSTime /config/guacamole/data/log/ 这个目录不存在会由 guacamole 启动后自动创建

**Comment by OPSTime** [comment]
他要是创建就不会有启动报那个错误了
