### ISSUE TITLE
容器外面的目录为什么不配置到env里面？

### ISSUE THREAD

**Issue by yinglian-litao** [jumpserver/Dockerfile#70]
**JumpServer 版本(v1.5.9以下不再支持)**
容器外面的目录为什么不配置到env里面？

**Bug 描述**
迁移时候很麻烦怎么放在docker目录下面/var/lib/docker/volumes/

**Comment by wojiushixiaobai** [comment]
@yinglian-litao 可以在 docker-compose.yml 里面自行指定
