### ISSUE TITLE
[Bug] jumpserver/nginx:v2.17.1 不存在

### ISSUE THREAD

**Issue by thinktkj** [jumpserver/Dockerfile#99]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
docker pull jumpserver/jms_nginx:v2.17.1 存在

docker pull jumpserver/nginx:v2.17.1 不存在

是不是忘记迁移最新的镜像了？

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
今天 github actions 有问题，构建一直失败。等明天再更新看看
